### ISSUE TITLE
How to custom the height of a tab content?

### ISSUE THREAD

**Issue by codlin** [Ali-Azmoud/vertical_tabs#1]
Hi, thanks for your share.
I want a vertical tab view is not always a whole screen, maybe more tab views combine together in one page, it depend on the content of a tab view. 
What should I do to achieve this goal? 
Thanks.

**Comment by Ali-Azmoud** [comment]
Hi
You should wrap your vertical tab with another widget and set it's height. Sorry it's not possible to calculate the height based on content. It's possible but for tabview which each one may contain different content and height, it's not going to has a good result.
