### ISSUE TITLE
希望可以获取_selectedIndex

### ISSUE THREAD

**Issue by p-eng** [Ali-Azmoud/vertical_tabs#4]

**Comment by LoveRain1997** [comment]
如果要设置选中tab的Style的,我已经加到PR里面了.

**Comment by LoveRain1997** [comment]
> _No description provided._

如果要设置选中tab的Style的,我已经加到PR里面了.

**Comment by p-eng** [comment]
好的

**Comment by Ali-Azmoud** [comment]
Hi, Your request is available in the latest version. please update the package.
Google Translate ( 嗨，您的要求是最新版本。请更新软件包。 )
