### ISSUE TITLE
tab label text is faded if text is too long.

### ISSUE THREAD

**Issue by krishnavamshi3** [Ali-Azmoud/vertical_tabs#8]
Hi, Tab label text is faded if text is too long and even if we use itemExtent parameter, it is not a reliable solution as we dont know the exact text if redered dynamically from server.
You may try this solution and update if it works as needed:
* you can remove line 153 (CrossAxisAlignment.stretch) as it stretches the item to indefinitly and it will be an error if the widget is under any non-constrained widget.
* you can remove line 102 (itemExtent: widget.itemExtent,) as it forces the children to have the given extent in the scroll direction [as per docs.]
* you can remove line 158. now we can avoid specifying exact height of the container.

using itemExtent is not a good idea if the data is dynamic.

Hope this may be useful.

**Comment by Ali-Azmoud** [comment]
Hi, thanks for your solution.
In the latest version you can have multi line labels. I'm going to close this issue, feel free to open it if you need to
